// default package
// Generated Jun 7, 2014 3:29:52 PM by Hibernate Tools 3.4.0.CR1

package com.secure.Modal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BseTable generated by hbm2java
 */
@Entity
@Table(name = "bse_table", catalog = "productd_securebank")
public class BseTable implements java.io.Serializable {

	private Long bseTableId;
	private String companyQuote;
	private String companyName;
	private String sectorType;
	private Double open;
	private Double prevClose;
	private Double high;
	private Double low;
	private Double gain;
	private Set<WatchlistBse> watchlistBses = new HashSet<WatchlistBse>(0);
	private Set<UserBseStock> userBseStocks = new HashSet<UserBseStock>(0);

	public BseTable() {
	}

	public BseTable(String companyQuote, String companyName, String sectorType,
			Double open, Double prevClose, Double high, Double low,
			Double gain, Set<WatchlistBse> watchlistBses,
			Set<UserBseStock> userBseStocks) {
		this.companyQuote = companyQuote;
		this.companyName = companyName;
		this.sectorType = sectorType;
		this.open = open;
		this.prevClose = prevClose;
		this.high = high;
		this.low = low;
		this.gain = gain;
		this.watchlistBses = watchlistBses;
		this.userBseStocks = userBseStocks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bse_table_id", unique = true, nullable = false)
	public Long getBseTableId() {
		return this.bseTableId;
	}

	public void setBseTableId(Long bseTableId) {
		this.bseTableId = bseTableId;
	}

	@Column(name = "company_quote", length = 50)
	public String getCompanyQuote() {
		return this.companyQuote;
	}

	public void setCompanyQuote(String companyQuote) {
		this.companyQuote = companyQuote;
	}

	@Column(name = "company_name", length = 50)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "sector_type", length = 50)
	public String getSectorType() {
		return this.sectorType;
	}

	public void setSectorType(String sectorType) {
		this.sectorType = sectorType;
	}

	@Column(name = "open", precision = 22, scale = 0)
	public Double getOpen() {
		return this.open;
	}

	public void setOpen(Double open) {
		this.open = open;
	}

	@Column(name = "prev_close", precision = 22, scale = 0)
	public Double getPrevClose() {
		return this.prevClose;
	}

	public void setPrevClose(Double prevClose) {
		this.prevClose = prevClose;
	}

	@Column(name = "high", precision = 22, scale = 0)
	public Double getHigh() {
		return this.high;
	}

	public void setHigh(Double high) {
		this.high = high;
	}

	@Column(name = "low", precision = 22, scale = 0)
	public Double getLow() {
		return this.low;
	}

	public void setLow(Double low) {
		this.low = low;
	}

	@Column(name = "gain", precision = 22, scale = 0)
	public Double getGain() {
		return this.gain;
	}

	public void setGain(Double gain) {
		this.gain = gain;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bseTable")
	public Set<WatchlistBse> getWatchlistBses() {
		return this.watchlistBses;
	}

	public void setWatchlistBses(Set<WatchlistBse> watchlistBses) {
		this.watchlistBses = watchlistBses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bseTable")
	public Set<UserBseStock> getUserBseStocks() {
		return this.userBseStocks;
	}

	public void setUserBseStocks(Set<UserBseStock> userBseStocks) {
		this.userBseStocks = userBseStocks;
	}

}
