// default package
// Generated Jun 7, 2014 3:29:52 PM by Hibernate Tools 3.4.0.CR1

package com.secure.Modal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CommonTable generated by hbm2java
 */
@Entity
@Table(name = "common_table", catalog = "productd_securebank")
public class CommonTable implements java.io.Serializable {

	private Long commonTableId;
	private String stockQuote;
	private Double open;
	private Double prevClose;
	private Double high;
	private Double low;
	private Double gain;

	public CommonTable() {
	}

	public CommonTable(String stockQuote, Double open, Double prevClose,
			Double high, Double low, Double gain) {
		this.stockQuote = stockQuote;
		this.open = open;
		this.prevClose = prevClose;
		this.high = high;
		this.low = low;
		this.gain = gain;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "common_table_id", unique = true, nullable = false)
	public Long getCommonTableId() {
		return this.commonTableId;
	}

	public void setCommonTableId(Long commonTableId) {
		this.commonTableId = commonTableId;
	}

	@Column(name = "stock_quote", length = 50)
	public String getStockQuote() {
		return this.stockQuote;
	}

	public void setStockQuote(String stockQuote) {
		this.stockQuote = stockQuote;
	}

	@Column(name = "open", precision = 22, scale = 0)
	public Double getOpen() {
		return this.open;
	}

	public void setOpen(Double open) {
		this.open = open;
	}

	@Column(name = "prev_close", precision = 22, scale = 0)
	public Double getPrevClose() {
		return this.prevClose;
	}

	public void setPrevClose(Double prevClose) {
		this.prevClose = prevClose;
	}

	@Column(name = "high", precision = 22, scale = 0)
	public Double getHigh() {
		return this.high;
	}

	public void setHigh(Double high) {
		this.high = high;
	}

	@Column(name = "low", precision = 22, scale = 0)
	public Double getLow() {
		return this.low;
	}

	public void setLow(Double low) {
		this.low = low;
	}

	@Column(name = "gain", precision = 22, scale = 0)
	public Double getGain() {
		return this.gain;
	}

	public void setGain(Double gain) {
		this.gain = gain;
	}

}
