// default package
// Generated Jun 7, 2014 3:29:52 PM by Hibernate Tools 3.4.0.CR1

package com.secure.Modal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CustomerTable generated by hbm2java
 */
@Entity
@Table(name = "customer_table", catalog = "productd_securebank")
public class CustomerTable implements java.io.Serializable {

	private Long customerTableId;
	private String userName;
	private String password;
	private String mailId;
	private String phoneNo;
	private Set<LoginStatusTable> loginStatusTables = new HashSet<LoginStatusTable>(
			0);
	private Set<WatchlistBse> watchlistBses = new HashSet<WatchlistBse>(0);
	private Set<PortfolioTable> portfolioTables = new HashSet<PortfolioTable>(0);
	private Set<WatchlistNse> watchlistNses = new HashSet<WatchlistNse>(0);

	public CustomerTable() {
	}

	public CustomerTable(String userName, String password, String mailId,
			String phoneNo, Set<LoginStatusTable> loginStatusTables,
			Set<WatchlistBse> watchlistBses,
			Set<PortfolioTable> portfolioTables, Set<WatchlistNse> watchlistNses) {
		this.userName = userName;
		this.password = password;
		this.mailId = mailId;
		this.phoneNo = phoneNo;
		this.loginStatusTables = loginStatusTables;
		this.watchlistBses = watchlistBses;
		this.portfolioTables = portfolioTables;
		this.watchlistNses = watchlistNses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "customer_table_id", unique = true, nullable = false)
	public Long getCustomerTableId() {
		return this.customerTableId;
	}

	public void setCustomerTableId(Long customerTableId) {
		this.customerTableId = customerTableId;
	}

	@Column(name = "user_name", length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", length = 25)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "mail_id", length = 25)
	public String getMailId() {
		return this.mailId;
	}

	public void setMailId(String mailId) {
		this.mailId = mailId;
	}

	@Column(name = "phone_no", length = 11)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerTable")
	public Set<LoginStatusTable> getLoginStatusTables() {
		return this.loginStatusTables;
	}

	public void setLoginStatusTables(Set<LoginStatusTable> loginStatusTables) {
		this.loginStatusTables = loginStatusTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerTable")
	public Set<WatchlistBse> getWatchlistBses() {
		return this.watchlistBses;
	}

	public void setWatchlistBses(Set<WatchlistBse> watchlistBses) {
		this.watchlistBses = watchlistBses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerTable")
	public Set<PortfolioTable> getPortfolioTables() {
		return this.portfolioTables;
	}

	public void setPortfolioTables(Set<PortfolioTable> portfolioTables) {
		this.portfolioTables = portfolioTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerTable")
	public Set<WatchlistNse> getWatchlistNses() {
		return this.watchlistNses;
	}

	public void setWatchlistNses(Set<WatchlistNse> watchlistNses) {
		this.watchlistNses = watchlistNses;
	}

}
