// default package
// Generated Jun 7, 2014 3:29:52 PM by Hibernate Tools 3.4.0.CR1

package com.secure.Modal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LoginStatusTable generated by hbm2java
 */
@Entity
@Table(name = "login_status_table", catalog = "productd_securebank")
public class LoginStatusTable implements java.io.Serializable {

	private Long loginStatusTableId;
	private CustomerTable customerTable;
	private Byte status;

	public LoginStatusTable() {
	}

	public LoginStatusTable(CustomerTable customerTable, Byte status) {
		this.customerTable = customerTable;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "login_status_table_id", unique = true, nullable = false)
	public Long getLoginStatusTableId() {
		return this.loginStatusTableId;
	}

	public void setLoginStatusTableId(Long loginStatusTableId) {
		this.loginStatusTableId = loginStatusTableId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_table_id")
	public CustomerTable getCustomerTable() {
		return this.customerTable;
	}

	public void setCustomerTable(CustomerTable customerTable) {
		this.customerTable = customerTable;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
