// default package
// Generated Jun 7, 2014 3:29:52 PM by Hibernate Tools 3.4.0.CR1

package com.secure.Modal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PortfolioTable generated by hbm2java
 */
@Entity
@Table(name = "portfolio_table", catalog = "productd_securebank")
public class PortfolioTable implements java.io.Serializable {

	private Long portfolioTableId;
	private CustomerTable customerTable;
	private String portfolioName;
	private Set<UserBseStock> userBseStocks = new HashSet<UserBseStock>(0);

	public PortfolioTable() {
	}

	public PortfolioTable(CustomerTable customerTable, String portfolioName,
			Set<UserBseStock> userBseStocks) {
		this.customerTable = customerTable;
		this.portfolioName = portfolioName;
		this.userBseStocks = userBseStocks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "portfolio_table_id", unique = true, nullable = false)
	public Long getPortfolioTableId() {
		return this.portfolioTableId;
	}

	public void setPortfolioTableId(Long portfolioTableId) {
		this.portfolioTableId = portfolioTableId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_table_id")
	public CustomerTable getCustomerTable() {
		return this.customerTable;
	}

	public void setCustomerTable(CustomerTable customerTable) {
		this.customerTable = customerTable;
	}

	@Column(name = "portfolio_name", length = 40)
	public String getPortfolioName() {
		return this.portfolioName;
	}

	public void setPortfolioName(String portfolioName) {
		this.portfolioName = portfolioName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "portfolioTable")
	public Set<UserBseStock> getUserBseStocks() {
		return this.userBseStocks;
	}

	public void setUserBseStocks(Set<UserBseStock> userBseStocks) {
		this.userBseStocks = userBseStocks;
	}

}
