// default package
// Generated Jun 7, 2014 3:29:52 PM by Hibernate Tools 3.4.0.CR1

package com.secure.Modal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserNseStock generated by hbm2java
 */
@Entity
@Table(name = "user_nse_stock", catalog = "productd_securebank")
public class UserNseStock implements java.io.Serializable {

	private Long userStockId;
	private NseTable nseTable;
	private Double buyingRate;
	private Double profitLoss;
	private Integer quantity;
	private Date purchaseDate;
	private Long portfolioTableId;

	public UserNseStock() {
	}

	public UserNseStock(NseTable nseTable, Double buyingRate,
			Double profitLoss, Integer quantity, Date purchaseDate,
			Long portfolioTableId) {
		this.nseTable = nseTable;
		this.buyingRate = buyingRate;
		this.profitLoss = profitLoss;
		this.quantity = quantity;
		this.purchaseDate = purchaseDate;
		this.portfolioTableId = portfolioTableId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_stock_id", unique = true, nullable = false)
	public Long getUserStockId() {
		return this.userStockId;
	}

	public void setUserStockId(Long userStockId) {
		this.userStockId = userStockId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nse_table_id")
	public NseTable getNseTable() {
		return this.nseTable;
	}

	public void setNseTable(NseTable nseTable) {
		this.nseTable = nseTable;
	}

	@Column(name = "buying_rate", precision = 22, scale = 0)
	public Double getBuyingRate() {
		return this.buyingRate;
	}

	public void setBuyingRate(Double buyingRate) {
		this.buyingRate = buyingRate;
	}

	@Column(name = "profit_loss", precision = 22, scale = 0)
	public Double getProfitLoss() {
		return this.profitLoss;
	}

	public void setProfitLoss(Double profitLoss) {
		this.profitLoss = profitLoss;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "purchase_date", length = 0)
	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	@Column(name = "portfolio_table_id")
	public Long getPortfolioTableId() {
		return this.portfolioTableId;
	}

	public void setPortfolioTableId(Long portfolioTableId) {
		this.portfolioTableId = portfolioTableId;
	}

}
