// default package
// Generated Jun 7, 2014 3:29:52 PM by Hibernate Tools 3.4.0.CR1

package com.secure.Modal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserBseStock generated by hbm2java
 */
@Entity
@Table(name = "user_bse_stock", catalog = "productd_securebank")
public class UserBseStock implements java.io.Serializable {

	private Long userStockId;
	private BseTable bseTable;
	private PortfolioTable portfolioTable;
	private Double buyingRate;
	private Double profitLoss;
	private Integer quantity;
	private Date purchaseDate;

	public UserBseStock() {
	}

	public UserBseStock(BseTable bseTable, PortfolioTable portfolioTable,
			Double buyingRate, Double profitLoss, Integer quantity,
			Date purchaseDate) {
		this.bseTable = bseTable;
		this.portfolioTable = portfolioTable;
		this.buyingRate = buyingRate;
		this.profitLoss = profitLoss;
		this.quantity = quantity;
		this.purchaseDate = purchaseDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_stock_id", unique = true, nullable = false)
	public Long getUserStockId() {
		return this.userStockId;
	}

	public void setUserStockId(Long userStockId) {
		this.userStockId = userStockId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bse_table_id")
	public BseTable getBseTable() {
		return this.bseTable;
	}

	public void setBseTable(BseTable bseTable) {
		this.bseTable = bseTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "portfolio_table_id")
	public PortfolioTable getPortfolioTable() {
		return this.portfolioTable;
	}

	public void setPortfolioTable(PortfolioTable portfolioTable) {
		this.portfolioTable = portfolioTable;
	}

	@Column(name = "buying_rate", precision = 22, scale = 0)
	public Double getBuyingRate() {
		return this.buyingRate;
	}

	public void setBuyingRate(Double buyingRate) {
		this.buyingRate = buyingRate;
	}

	@Column(name = "profit_loss", precision = 22, scale = 0)
	public Double getProfitLoss() {
		return this.profitLoss;
	}

	public void setProfitLoss(Double profitLoss) {
		this.profitLoss = profitLoss;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "purchase_date", length = 0)
	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

}
