// default package
// Generated Jun 7, 2014 3:29:52 PM by Hibernate Tools 3.4.0.CR1

package com.secure.Modal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WatchlistBse generated by hbm2java
 */
@Entity
@Table(name = "watchlist_bse", catalog = "productd_securebank")
public class WatchlistBse implements java.io.Serializable {

	private Long watchlistBseId;
	private CustomerTable customerTable;
	private BseTable bseTable;
	private Double alertAbove;
	private Double alertBelow;

	public WatchlistBse() {
	}

	public WatchlistBse(CustomerTable customerTable, BseTable bseTable,
			Double alertAbove, Double alertBelow) {
		this.customerTable = customerTable;
		this.bseTable = bseTable;
		this.alertAbove = alertAbove;
		this.alertBelow = alertBelow;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "watchlist_bse_id", unique = true, nullable = false)
	public Long getWatchlistBseId() {
		return this.watchlistBseId;
	}

	public void setWatchlistBseId(Long watchlistBseId) {
		this.watchlistBseId = watchlistBseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_table_id")
	public CustomerTable getCustomerTable() {
		return this.customerTable;
	}

	public void setCustomerTable(CustomerTable customerTable) {
		this.customerTable = customerTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bse_table_id")
	public BseTable getBseTable() {
		return this.bseTable;
	}

	public void setBseTable(BseTable bseTable) {
		this.bseTable = bseTable;
	}

	@Column(name = "alert_above", precision = 22, scale = 0)
	public Double getAlertAbove() {
		return this.alertAbove;
	}

	public void setAlertAbove(Double alertAbove) {
		this.alertAbove = alertAbove;
	}

	@Column(name = "alert_below", precision = 22, scale = 0)
	public Double getAlertBelow() {
		return this.alertBelow;
	}

	public void setAlertBelow(Double alertBelow) {
		this.alertBelow = alertBelow;
	}

}
